# Working with the OASIS-1 cross-sectional dataset in pandas

**Goal of this notebook:** get comfortable with the dataset *before* we run any statistics. We will

1. load the data and check its shape
2. look at the columns and the first rows
3. learn three ways to access elements of a table
4. check how many entries a column has and how many different values it takes
5. replace text with numbers (mapping), plus a bonus on one-hot encoding

**Data:** `oasis_cross-sectional.csv` (Marcus et al., 2007, *Journal of Cognitive Neuroscience*). Place the file in the same folder as this notebook.

Cells marked **Question** are for you to think about before reading on. Cells marked **Your turn** are small exercises.

In [2]:
import pandas as pd
import numpy as np
from pprint import pprint

## 1. Loading the dataset

`pd.read_csv` reads a CSV file into a **DataFrame**, pandas' table type (think of a spreadsheet inside Python). We store it in a variable called `df`.

In [3]:
df = pd.read_csv("oasis_cross-sectional.csv")

### Inspecting the shape

`.shape` returns a tuple `(number of rows, number of columns)`. Always check this right after loading: does it match what you expect from the documentation?

In [4]:
print(df.shape)
n_rows, n_cols = df.shape
print(f"The table has {n_rows} rows and {n_cols} columns.")

(436, 12)
The table has 436 rows and 12 columns.

> **Question:** The OASIS fact sheet says the dataset contains **416 subjects**. What do you notice? Keep this in mind, we will come back to it in section 5.

## 2. Looking at the columns

In [5]:
df.columns

Index(['ID', 'M/F', 'Hand', 'Age', 'Educ', 'SES', 'MMSE', 'CDR', 'eTIV',
       'nWBV', 'ASF', 'Delay'],
      dtype='str')

In [6]:
list(df.columns)

['ID',
 'M/F',
 'Hand',
 'Age',
 'Educ',
 'SES',
 'MMSE',
 'CDR',
 'eTIV',
 'nWBV',
 'ASF',
 'Delay']

What each column holds (from the OASIS fact sheet and the Marcus et al. paper):

| Column | Meaning | Values |
|---|---|---|
| `ID` | Session identifier; `MR1` = first scan session, `MR2` = a repeat session | text, e.g. `OAS1_0001_MR1` |
| `M/F` | Sex | `M`, `F` |
| `Hand` | Handedness | `R` (all participants are right-handed) |
| `Age` | Age in years | 18 to 96 |
| `Educ` | Education level | 1 = less than high school, 2 = high school grad, 3 = some college, 4 = college grad, 5 = beyond college |
| `SES` | Socioeconomic status | 1 to 5 (**1 = highest, 5 = lowest** status; check the Marcus et al. paper to confirm) |
| `MMSE` | Mini-Mental State Examination, a cognitive screening score | 0 to 30, higher = better |
| `CDR` | Clinical Dementia Rating | 0 = nondemented, 0.5 = very mild, 1 = mild, 2 = moderate dementia |
| `eTIV` | Estimated total intracranial volume | mm³ |
| `nWBV` | Normalized whole-brain volume | proportion of the intracranial volume |
| `ASF` | Atlas scaling factor | unitless |
| `Delay` | Days between the first and the repeat scan | only filled for the repeat sessions |

pandas also records what *type* each column was read as:

In [7]:
df.dtypes

ID           str
M/F          str
Hand         str
Age        int64
Educ     float64
SES      float64
MMSE     float64
CDR      float64
eTIV       int64
nWBV     float64
ASF      float64
Delay    float64
dtype: object

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 436 entries, 0 to 435
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      436 non-null    str
 1   M/F     436 non-null    str
 2   Hand    436 non-null    str
 3   Age     436 non-null    int64
 4   Educ    235 non-null    float64
 5   SES     216 non-null    float64
 6   MMSE    235 non-null    float64
 7   CDR     235 non-null    float64
 8   eTIV    436 non-null    int64
 9   nWBV    436 non-null    float64
 10  ASF     436 non-null    float64
 11  Delay   20 non-null     float64
dtypes: float64(7), int64(2), str(3)
memory usage: 41.0 KB

> **Question:** Look at the `Non-Null Count` column in the output above. Do all columns have the same number of entries? Why might some be lower?

## 3. Viewing the first rows

`.head()` shows the first 5 rows by default; pass a number to see more. `.tail()` shows the last rows.

In [9]:
df.head()

,ID,M/F,Hand,Age,Educ,SES,MMSE,CDR,eTIV,nWBV,ASF,Delay
0,OAS1_0001_MR1,F,R,74,2.0,3.0,29.0,0.0,1344,0.743,1.306,NaN
1,OAS1_0002_MR1,F,R,55,4.0,1.0,29.0,0.0,1147,0.810,1.531,NaN
2,OAS1_0003_MR1,F,R,73,4.0,3.0,27.0,0.5,1454,0.708,1.207,NaN
3,OAS1_0004_MR1,M,R,28,NaN,NaN,NaN,NaN,1588,0.803,1.105,NaN
4,OAS1_0005_MR1,M,R,18,NaN,NaN,NaN,NaN,1737,0.848,1.010,NaN

In [10]:
df.head(10)

,ID,M/F,Hand,Age,Educ,SES,MMSE,CDR,eTIV,nWBV,ASF,Delay
0,OAS1_0001_MR1,F,R,74,2.0,3.0,29.0,0.0,1344,0.743,1.306,NaN
1,OAS1_0002_MR1,F,R,55,4.0,1.0,29.0,0.0,1147,0.810,1.531,NaN
2,OAS1_0003_MR1,F,R,73,4.0,3.0,27.0,0.5,1454,0.708,1.207,NaN
3,OAS1_0004_MR1,M,R,28,NaN,NaN,NaN,NaN,1588,0.803,1.105,NaN
4,OAS1_0005_MR1,M,R,18,NaN,NaN,NaN,NaN,1737,0.848,1.010,NaN
5,OAS1_0006_MR1,F,R,24,NaN,NaN,NaN,NaN,1131,0.862,1.551,NaN
6,OAS1_0007_MR1,M,R,21,NaN,NaN,NaN,NaN,1516,0.830,1.157,NaN
7,OAS1_0009_MR1,F,R,20,NaN,NaN,NaN,NaN,1505,0.843,1.166,NaN
8,OAS1_0010_MR1,M,R,74,5.0,2.0,30.0,0.0,1636,0.689,1.073,NaN
9,OAS1_0011_MR1,F,R,52,3.0,2.0,30.0,0.0,1321,0.827,1.329,NaN

In [11]:
df.tail()

,ID,M/F,Hand,Age,Educ,SES,MMSE,CDR,eTIV,nWBV,ASF,Delay
431,OAS1_0285_MR2,M,R,20,NaN,NaN,NaN,NaN,1469,0.847,1.195,2.0
432,OAS1_0353_MR2,M,R,22,NaN,NaN,NaN,NaN,1684,0.790,1.042,40.0
433,OAS1_0368_MR2,M,R,22,NaN,NaN,NaN,NaN,1580,0.856,1.111,89.0
434,OAS1_0379_MR2,F,R,20,NaN,NaN,NaN,NaN,1262,0.861,1.390,2.0
435,OAS1_0395_MR2,F,R,26,NaN,NaN,NaN,NaN,1283,0.834,1.368,39.0

`NaN` ("not a number") is how pandas marks a **missing value**. Notice that the younger participants in the first 10 rows have `NaN` for `Educ`, `SES`, `MMSE` and `CDR`. We will investigate why in section 5.

## 4. Structure of a DataFrame and how to access elements

A DataFrame is a collection of **columns**, where each column is a **Series** (a labelled list of values). Every row has an **index label** (here `0, 1, 2, ...`) and every column has a **name**.

In [12]:
print(type(df))
print(type(df["Age"]))

<class 'pandas.DataFrame'>
<class 'pandas.Series'>

In [13]:
df["Age"].head()

0    74
1    55
2    73
3    28
4    18
Name: Age, dtype: int64

The numbers on the left are the index labels. There are three common ways to pick out a single value. As an example, we will get the **age of the first participant** with each of them.

### 4a. Column name first, then index

`df["Age"]` gives the whole column (a Series), and `[0]` then picks the entry with **index label** 0.

In [14]:
df["Age"][0]

np.int64(74)

In [15]:
df["Age"][0:5]   # a slice of the column

0    74
1    55
2    73
3    28
4    18
Name: Age, dtype: int64

### 4b. By position, like a matrix: `.iloc[row, column]`

`iloc` stands for **integer location**. You give *row number, column number*, counting from **0**, exactly as in a matrix. `Age` is the 4th column, so its position is 3.

In [16]:
df.iloc[0, 3]

np.int64(74)

In [17]:
df.iloc[0:5, 2:5]   # rows 0-4 and columns 2-4: the end of the range is EXCLUDED

  Hand  Age  Educ
0    R   74   2.0
1    R   55   4.0
2    R   73   4.0
3    R   28   NaN
4    R   18   NaN

In [18]:
df.iloc[0]          # a whole row (the first participant)

ID       OAS1_0001_MR1
M/F                  F
Hand                 R
Age                 74
Educ               2.0
SES                3.0
MMSE              29.0
CDR                0.0
eTIV              1344
nWBV             0.743
ASF              1.306
Delay              NaN
Name: 0, dtype: object

### 4c. Row first, then column name: `.loc[row, column name]`

`loc` stands for **label location**. You give the row's *index label* and the column's *name*.

In [19]:
df.loc[0, "Age"]

np.int64(74)

In [20]:
df.loc[0:4, ["Age", "MMSE"]]   # careful: with .loc the end of the range is INCLUDED

   Age  MMSE
0   74  29.0
1   55  29.0
2   73  27.0
3   28   NaN
4   18   NaN

In [21]:
# All three ways return the same value:
print(df["Age"][0], df.iloc[0, 3], df.loc[0, "Age"])

74 74 74

### Summary

| Method | You provide | Counting | End of a slice |
|---|---|---|---|
| `df["Age"][0]` | column name, then index label | by label | label-based |
| `df.iloc[0, 3]` | row position, column position | from 0 | **excluded** |
| `df.loc[0, "Age"]` | row label, column name | by label | **included** |

### A pitfall: labels and positions are not always the same

Right now, the label of each row equals its position, so the three methods agree. As soon as we **filter** the table, this changes.

In [22]:
oldest = df[df["Age"] >= 90]   # keep only participants aged 90 or older
oldest.head(3)

,ID,M/F,Hand,Age,Educ,SES,MMSE,CDR,eTIV,nWBV,ASF,Delay
60,OAS1_0065_MR1,M,R,90,2.0,3.0,25.0,0.0,1301,0.645,1.349,NaN
78,OAS1_0083_MR1,F,R,90,5.0,3.0,27.0,0.0,1200,0.727,1.462,NaN
201,OAS1_0221_MR1,F,R,94,5.0,1.0,29.0,0.0,1474,0.696,1.190,NaN

The index labels of the filtered table are no longer `0, 1, 2`. Now what happens?

In [23]:
print(oldest.iloc[0, 3])        # first row *by position*: works
print(oldest.loc[oldest.index[0], "Age"])   # first row *by label*: works, we looked up the label

90
90

In [24]:
try:
    print(oldest.loc[0, "Age"])  # label 0 was filtered out
except KeyError as e:
    print("KeyError: there is no row with label", e)

KeyError: there is no row with label 0

> **Rule of thumb:** use `.iloc` when you mean "the n-th row" and `.loc` when you mean "the row with this label". Both are safer than the chained form `df["Age"][0]`, which is fine for quick looks.

> **Your turn:** Get the `MMSE` score of the participant in the 3rd row (position 2) with all three methods.

In [25]:
# your code here

## 5. Inspecting a single column

We focus on the columns that matter most for our later analyses: `M/F`, `Educ`, `SES`, `MMSE`, and `CDR`.

### 5a. How many entries are there?

Two numbers are useful:
- `len(df)` is the number of **rows**, including missing values
- `df["col"].count()` is the number of **non-missing** entries in that column

In [26]:
print("Rows in the table:        ", len(df))
print("Entries in the SES column:", df["SES"].count())
print("Missing in the SES column:", df["SES"].isna().sum())

Rows in the table:         436
Entries in the SES column: 216
Missing in the SES column: 220

In [27]:
cols = ["M/F", "Educ", "SES", "MMSE", "CDR"]

summary = pd.DataFrame({
    "entries": df[cols].count(),
    "missing": df[cols].isna().sum(),
})
summary["% missing"] = (summary["missing"] / len(df) * 100).round(1)
summary

      entries  missing  % missing
M/F       436        0        0.0
Educ      235      201       46.1
SES       216      220       50.5
MMSE      235      201       46.1
CDR       235      201       46.1

> **Question:** The documentation says there are 416 subjects, but the table has 436 rows, and `SES` has even fewer entries (216). How can both differences be explained?
>
> Think about it first, then run the next cells to check your hypotheses.

**Hypothesis 1: some subjects appear more than once.** The `ID` column ends in `_MR1` or `_MR2`. Let's count the sessions and the unique subjects.

In [28]:
df["ID"].str[-3:].value_counts()

ID
MR1    416
MR2     20
Name: count, dtype: int64

In [29]:
# the subject ID is everything before the last underscore
df["subject"] = df["ID"].str.rsplit("_", n=1).str[0]
print("Unique subjects:", df["subject"].nunique())

Unique subjects: 416

In [30]:
df[df["Delay"].notna()].head()   # the repeat sessions

,ID,M/F,Hand,Age,Educ,SES,MMSE,CDR,eTIV,nWBV,ASF,Delay,subject
416,OAS1_0061_MR2,F,R,20,NaN,NaN,NaN,NaN,1757,0.845,0.999,1.0,OAS1_0061
417,OAS1_0080_MR2,F,R,25,NaN,NaN,NaN,NaN,1605,0.841,1.093,20.0,OAS1_0080
418,OAS1_0092_MR2,M,R,22,NaN,NaN,NaN,NaN,1457,0.835,1.205,5.0,OAS1_0092
419,OAS1_0101_MR2,M,R,29,NaN,NaN,NaN,NaN,1501,0.835,1.169,64.0,OAS1_0101
420,OAS1_0111_MR2,M,R,23,NaN,NaN,NaN,NaN,1714,0.861,1.024,2.0,OAS1_0111

The 20 extra rows are **repeat scan sessions** (`MR2`) of 20 non-demented subjects, done within 90 days to assess scan reliability. So 436 rows = 416 subjects + 20 repeat sessions. (This also means the rows are **not independent**, which matters later when we apply statistical tests.)

**Hypothesis 2: the clinical variables were not recorded for everyone.** Let's compare the ages of rows with and without an `MMSE` score.

In [31]:
df.groupby(df["MMSE"].isna())["Age"].describe()

       count       mean        std   min   25%   50%   75%   max
MMSE
False  235.0  72.344681  12.091369  33.0  66.0  73.0  81.0  96.0
True   201.0  26.820896   9.758471  18.0  20.0  23.0  28.0  58.0

In [32]:
df.loc[df["MMSE"].notna(), "Age"].min(), df.loc[df["MMSE"].isna(), "Age"].max()

(np.int64(33), np.int64(58))

Every participant without an `MMSE` score is **58 or younger**, while scores exist for ages 33 to 96 (mostly older adults). The clinical assessments (`MMSE`, `CDR`) were thus collected almost exclusively for older participants, and `Educ`/`SES` follow the same pattern. These values are therefore **not missing at random**, which is something to keep in mind when we analyse them.

Also note that `SES` has fewer entries (216) than `Educ` and `MMSE` (235): some participants who were assessed lack an SES score. The next cell counts them.

In [33]:
# Participants who have Educ but no SES:
df[df["Educ"].notna() & df["SES"].isna()].shape[0]

19

### 5b. How many unique values can a column take?

- `.nunique()` counts the distinct values (ignoring `NaN` by default)
- `.unique()` lists them
- `.value_counts()` lists them *and* counts how often each occurs. Pass `dropna=False` to count the `NaN`s as well.

In [34]:
df["CDR"].nunique()

4

In [35]:
df["CDR"].unique()

array([0. , 0.5, nan, 1. , 2. ])

In [36]:
df["CDR"].value_counts(dropna=False)

CDR
NaN    201
0.0    135
0.5     70
1.0     28
2.0      2
Name: count, dtype: int64

In [37]:
df["CDR"].value_counts(dropna=False).sort_index()   # sorted by value instead of by count

CDR
0.0    135
0.5     70
1.0     28
2.0      2
NaN    201
Name: count, dtype: int64

Now for all five columns at once:

In [38]:
for col in cols:
    print(f"{col:>5}: {df[col].nunique():>2} unique values -> {sorted(df[col].dropna().unique())}")

  M/F:  2 unique values -> ['F', 'M']
 Educ:  5 unique values -> [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0)]
  SES:  5 unique values -> [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0)]
 MMSE: 17 unique values -> [np.float64(14.0), np.float64(15.0), np.float64(16.0), np.float64(17.0), np.float64(18.0), np.float64(19.0), np.float64(20.0), np.float64(21.0), np.float64(22.0), np.float64(23.0), np.float64(24.0), np.float64(25.0), np.float64(26.0), np.float64(27.0), np.float64(28.0), np.float64(29.0), np.float64(30.0)]
  CDR:  4 unique values -> [np.float64(0.0), np.float64(0.5), np.float64(1.0), np.float64(2.0)]

> **Question:** What do the numbers of unique values tell you about the type of each variable (nominal, ordinal, continuous)? Is `MMSE` ordinal, continuous, or something in between?

For comparison, here are two other columns:

In [39]:
print("Hand:", df["Hand"].unique())
print("Age: ", df["Age"].nunique(), "unique values")

Hand: <StringArray>
['R']
Length: 1, dtype: str
Age:  73 unique values

A column with a **single** unique value (`Hand`) carries no information for a statistical comparison: nothing varies.

> **Your turn:** How many unique values does `eTIV` have? Is it a sensible candidate for `value_counts()`?

In [40]:
# your code here

## 6. Mapping: replacing text with numbers

Many analyses need numeric inputs. Mapping means replacing each value with a chosen replacement. In pandas we do it with a **dictionary** and `.map()`:

```python
{old_value: new_value, ...}
```

### 6a. Nominal variable: `M/F`

Sex is **nominal** (no order), stored as text. We map `F -> 0` and `M -> 1`.

In [41]:
sex_map = {"F": 0, "M": 1}

df["Sex_code"] = df["M/F"].map(sex_map)
df[["M/F", "Sex_code"]].head()

  M/F  Sex_code
0   F         0
1   F         0
2   F         0
3   M         1
4   M         1

Always **verify** a mapping. A cross-tabulation should show that every `F` became 0 and every `M` became 1:

In [42]:
pd.crosstab(df["M/F"], df["Sex_code"])

Sex_code    0    1
M/F
F         268    0
M           0  168

**Watch out:** `.map()` turns every value that is *not* in the dictionary into `NaN`. A typo silently destroys data:

In [43]:
bad_map = {"F": 0, "m": 1}          # lower-case "m" does not match "M"
print(df["M/F"].map(bad_map).isna().sum(), "values were lost")

168 values were lost

Good habit: after mapping, check that you introduced no new missing values.

In [44]:
assert df["Sex_code"].isna().sum() == df["M/F"].isna().sum()
print("No values were lost.")

No values were lost.

### 6b. Ordinal variables: `CDR`, `Educ`, `SES`

For ordinal variables the numbers should **respect the order**. Three situations come up:

**(i) Turning odd codes into ranks.** `CDR` has the values 0, 0.5, 1, 2, so the steps are not equal. Mapping to ranks 0, 1, 2, 3 gives a clean ordinal scale. (Whether to treat the gaps as equal is a decision you should make consciously.)

In [45]:
cdr_rank_map = {0.0: 0, 0.5: 1, 1.0: 2, 2.0: 3}

df["CDR_rank"] = df["CDR"].map(cdr_rank_map)
pd.crosstab(df["CDR"], df["CDR_rank"])

CDR_rank  0.0  1.0  2.0  3.0
CDR
0.0       135    0    0    0
0.5         0   70    0    0
1.0         0    0   28    0
2.0         0    0    0    2

Note that `NaN` stays `NaN`: missing values are not in the dictionary, so they are not assigned a number. (`crosstab` hides them by default.)

**(ii) Attaching readable labels.** Mapping can also go from numbers to text, which makes tables and plots easier to read:

In [46]:
cdr_label_map = {0.0: "nondemented", 0.5: "very mild", 1.0: "mild", 2.0: "moderate"}
educ_label_map = {1: "< high school", 2: "high school grad", 3: "some college",
                  4: "college grad", 5: "beyond college"}

df["CDR_label"] = df["CDR"].map(cdr_label_map)
df["Educ_label"] = df["Educ"].map(educ_label_map)
df[["CDR", "CDR_label", "Educ", "Educ_label"]].dropna().head()

   CDR    CDR_label  Educ        Educ_label
0  0.0  nondemented   2.0  high school grad
1  0.0  nondemented   4.0      college grad
2  0.5    very mild   4.0      college grad
8  0.0  nondemented   5.0    beyond college
9  0.0  nondemented   3.0      some college

**(iii) Reversing a scale.** For `SES`, **1 = highest** and **5 = lowest** status, the opposite of `Educ`, where 5 = most education. That is confusing: a positive relationship between status and anything would show up as a *negative* correlation. We can create a reversed version where higher means higher status:

In [47]:
ses_reverse_map = {1: 5, 2: 4, 3: 3, 4: 2, 5: 1}

df["SES_reversed"] = df["SES"].map(ses_reverse_map)
pd.crosstab(df["SES"], df["SES_reversed"])

SES_reversed  1.0  2.0  3.0  4.0  5.0
SES
1.0             0    0    0    0   50
2.0             0    0    0   65    0
3.0             0    0   49    0    0
4.0             0   49    0    0    0
5.0             3    0    0    0    0

> **Question:** Compare the correlation of `Educ` with `SES` and with `SES_reversed`. What changes, and what stays the same?

In [48]:
print("Educ vs SES:         ", round(df["Educ"].corr(df["SES"]), 3))
print("Educ vs SES_reversed:", round(df["Educ"].corr(df["SES_reversed"]), 3))

Educ vs SES:          -0.742
Educ vs SES_reversed: 0.742

Only the **sign** flips; the strength is identical. This shows why you must know how a variable is coded before you interpret a result.

### 6c. Keeping a dictionary of your mappings

Months later you will not remember whether `M` was 0 or 1. Collect all mappings in **one dictionary** that serves as a codebook:

In [49]:
mappings = {
    "Sex_code":     {"F": 0, "M": 1},
    "CDR_rank":     {0.0: 0, 0.5: 1, 1.0: 2, 2.0: 3},
    "CDR_label":    {0.0: "nondemented", 0.5: "very mild", 1.0: "mild", 2.0: "moderate"},
    "Educ_label":   {1: "< high school", 2: "high school grad", 3: "some college",
                     4: "college grad", 5: "beyond college"},
    "SES_reversed": {1: 5, 2: 4, 3: 3, 4: 2, 5: 1},
}

pprint(mappings)

{'CDR_label': {0.0: 'nondemented',
               0.5: 'very mild',
               1.0: 'mild',
               2.0: 'moderate'},
 'CDR_rank': {0.0: 0, 0.5: 1, 1.0: 2, 2.0: 3},
 'Educ_label': {1: '< high school',
                2: 'high school grad',
                3: 'some college',
                4: 'college grad',
                5: 'beyond college'},
 'SES_reversed': {1: 5, 2: 4, 3: 3, 4: 2, 5: 1},
 'Sex_code': {'F': 0, 'M': 1}}

In [50]:
# Look up one mapping whenever you forget it:
mappings["Sex_code"]

{'F': 0, 'M': 1}

A mapping can be **inverted** to go back from the numbers to the original values:

In [51]:
inverse_sex_map = {number: text for text, number in mappings["Sex_code"].items()}
print(inverse_sex_map)

df["Sex_decoded"] = df["Sex_code"].map(inverse_sex_map)
print("Round trip successful:", (df["Sex_decoded"] == df["M/F"]).all())

{0: 'F', 1: 'M'}
Round trip successful: True

> **Your turn:** Create a column `Educ_college` that is `1` for participants with a college degree or higher (`Educ` 4 or 5) and `0` otherwise, using a dictionary and `.map()`. Add your mapping to the `mappings` codebook.

In [52]:
# your code here

## Extra: one-hot encoding

### The problem with numeric codes for nominal variables

Suppose a variable has three **unordered** categories, e.g. blood type A, B, O. If we code them 0, 1, 2, then any model will treat "O" as twice "B" and "B" as halfway between "A" and "O". That is meaningless for a nominal variable.

### The solution

**One-hot encoding** creates one new 0/1 column per category. A row has a `1` in the column of its category and `0` everywhere else.

In pandas: `pd.get_dummies()`. Our dataset has no unordered variable with more than two categories, so we use `CDR_label` purely as a demonstration.

In [53]:
onehot = pd.get_dummies(df["CDR_label"], prefix="CDR", dtype=int)
onehot.head(10)

   CDR_mild  CDR_moderate  CDR_nondemented  CDR_very mild
0         0             0                1              0
1         0             0                1              0
2         0             0                0              1
3         0             0                0              0
4         0             0                0              0
5         0             0                0              0
6         0             0                0              0
7         0             0                0              0
8         0             0                1              0
9         0             0                1              0

In [54]:
pd.concat([df[["CDR_label"]], onehot], axis=1).dropna().head()

     CDR_label  CDR_mild  CDR_moderate  CDR_nondemented  CDR_very mild
0  nondemented         0             0                1              0
1  nondemented         0             0                1              0
2    very mild         0             0                0              1
8  nondemented         0             0                1              0
9  nondemented         0             0                1              0

Every row (with a rating) should contain exactly one `1`:

In [55]:
row_sums = onehot.sum(axis=1)
print(row_sums.value_counts())

1    235
0    201
Name: count, dtype: int64

> **Question:** Some rows sum to **0**. Which ones, and why? What would go wrong if we didn't notice this?

Rows with a missing `CDR` get **all zeros**. By default, `get_dummies` does not create a "missing" category, so a participant with *no rating* looks the same as one that is "in none of the categories". You can handle this in two ways:

In [56]:
# Option 1: add an explicit "missing" column
pd.get_dummies(df["CDR_label"], prefix="CDR", dtype=int, dummy_na=True).head(5)

   CDR_mild  CDR_moderate  CDR_nondemented  CDR_very mild  CDR_nan
0         0             0                1              0        0
1         0             0                1              0        0
2         0             0                0              1        0
3         0             0                0              0        1
4         0             0                0              0        1

In [57]:
# Option 2: drop the rows with missing values first
pd.get_dummies(df["CDR_label"].dropna(), prefix="CDR", dtype=int).head(5)

   CDR_mild  CDR_moderate  CDR_nondemented  CDR_very mild
0         0             0                1              0
1         0             0                1              0
2         0             0                0              1
8         0             0                1              0
9         0             0                1              0

### The dummy variable trap: `drop_first`

If you know a participant is **not** in 3 of 4 categories, you automatically know they are in the fourth. The 4th column is redundant, and in a regression model with an intercept it causes perfect **multicollinearity**. The usual fix is to drop one column, which becomes the **reference category**:

In [58]:
pd.get_dummies(df["CDR_label"].dropna(), prefix="CDR", dtype=int, drop_first=True).head()

   CDR_moderate  CDR_nondemented  CDR_very mild
0             0                1              0
1             0                1              0
2             0                0              1
8             0                1              0
9             0                1              0

Note that `drop_first=True` drops the first category *alphabetically* (here "mild"). If you want a specific reference group (e.g. "nondemented"), drop that column yourself.

### When to use what?

| Variable type | Example | Encoding |
|---|---|---|
| Nominal, 2 categories | `M/F` | a single 0/1 column (what we did in 6a) |
| Nominal, 3+ categories | e.g. brain region, diagnosis group | one-hot encoding |
| Ordinal | `CDR`, `Educ`, `SES` | rank mapping (as in 6b), *or* one-hot if you do not want to assume equal spacing |
| Continuous | `Age`, `nWBV` | no encoding needed |

> **Your turn:** One-hot encode `Educ_label` (remember to deal with the missing values). How many columns do you get? Which would you drop as a reference?

In [59]:
# your code here

## Recap

- `pd.read_csv` loads the data, `.shape`, `.columns`, `.head()` and `.info()` give a first overview.
- Elements can be accessed via `df["col"][i]`, `df.iloc[row, col]` (positions, end excluded) and `df.loc[row, "col"]` (labels, end included).
- `len(df)` counts rows, `.count()` counts non-missing entries, `.nunique()` and `.value_counts()` show which values a column takes.
- Row count and subject count differ here because of **repeat sessions**; clinical variables are missing for the **younger participants**.
- `.map()` with a dictionary replaces values; always verify the result and keep a codebook dictionary.
- One-hot encoding (`pd.get_dummies`) is the way to encode nominal variables with 3+ categories without implying an order.